// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSSClientTickets.Models;

#nullable disable

namespace SSSClientTickets.Migrations
{
    [DbContext(typeof(SssclientContext))]
    [Migration("20260503163840_AddTicketBilled")]
    partial class AddTicketBilled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSSClientTickets.Models.Client", b =>
                {
                    b.Property<int>("ClientRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientRec"));

                    b.Property<string>("ClientAddr1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Client_Addr1");

                    b.Property<string>("ClientAddr2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Client_Addr2");

                    b.Property<string>("ClientCity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Client_City");

                    b.Property<string>("ClientName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Client_Name");

                    b.Property<string>("ClientState")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("Client_State")
                        .IsFixedLength();

                    b.Property<string>("ClientZip")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("Client_Zip")
                        .IsFixedLength();

                    b.Property<decimal>("HourlyRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("ClientRec");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("SSSClientTickets.Models.Customer", b =>
                {
                    b.Property<int>("CustomerRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerRec"));

                    b.Property<int>("ClientRec")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Customer_Name");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Customer_Email");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Customer_Mobile");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Customer_Phone");

                    b.HasKey("CustomerRec");

                    b.HasIndex("ClientRec");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("SSSClientTickets.Models.Site", b =>
                {
                    b.Property<int>("SiteRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteRec"));

                    b.Property<int>("ClientRec")
                        .HasColumnType("int");

                    b.Property<string>("SiteAddress1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Site_Address1");

                    b.Property<string>("SiteAddress2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Site_Address2");

                    b.Property<string>("SiteCity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Site_City");

                    b.Property<string>("SiteName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Site_Name");

                    b.Property<string>("SiteState")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Site_State");

                    b.Property<string>("SiteZip")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("Site_Zip")
                        .IsFixedLength();

                    b.HasKey("SiteRec");

                    b.HasIndex("ClientRec");

                    b.ToTable("Site", (string)null);
                });

            modelBuilder.Entity("SSSClientTickets.Models.Ticket", b =>
                {
                    b.Property<int>("TicketRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketRec"));

                    b.Property<DateTime?>("DateBilled")
                        .HasColumnType("datetime");

                    b.Property<int>("ClientRec")
                        .HasColumnType("int");

                    b.Property<int>("CustomerRec")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateLogged")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateResolved")
                        .HasColumnType("datetime");

                    b.Property<decimal>("HourlyRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Issue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SiteRec")
                        .HasColumnType("int");

                    b.Property<int>("StatusRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("TicketRec");

                    b.HasIndex("ClientRec");

                    b.HasIndex("CustomerRec");

                    b.HasIndex("SiteRec");

                    b.HasIndex("StatusRec");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("SSSClientTickets.Models.TicketAttachment", b =>
                {
                    b.Property<int>("AttachmentRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentRec"));

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsImage")
                        .HasColumnType("bit");

                    b.Property<int>("TicketRec")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AttachmentRec");

                    b.HasIndex("TicketRec");

                    b.ToTable("TicketAttachment", (string)null);
                });

            modelBuilder.Entity("SSSClientTickets.Models.TicketStatus", b =>
                {
                    b.Property<int>("StatusRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusRec"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StatusRec");

                    b.ToTable("TicketStatus", (string)null);

                    b.HasData(
                        new
                        {
                            StatusRec = 1,
                            Status = "Open"
                        },
                        new
                        {
                            StatusRec = 2,
                            Status = "In Progress"
                        },
                        new
                        {
                            StatusRec = 3,
                            Status = "Waiting for Client"
                        },
                        new
                        {
                            StatusRec = 4,
                            Status = "Resolved"
                        });
                });

            modelBuilder.Entity("SSSClientTickets.Models.TicketTime", b =>
                {
                    b.Property<int>("TimeRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeRec"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("TicketRec")
                        .HasColumnType("int");

                    b.HasKey("TimeRec");

                    b.HasIndex("TicketRec");

                    b.ToTable("TicketTime", (string)null);
                });

            modelBuilder.Entity("SSSClientTickets.Models.VwOpenTicket", b =>
                {
                    b.Property<string>("ClientName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Client_Name");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Customer_Name");

                    b.Property<string>("Issue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TicketRec")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_OpenTickets", (string)null);
                });

            modelBuilder.Entity("SSSClientTickets.Models.VwTicketTime", b =>
                {
                    b.Property<int>("TicketRec")
                        .HasColumnType("int");

                    b.Property<int?>("TotalMinutes")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_TicketTime", (string)null);
                });

            modelBuilder.Entity("SSSClientTickets.Models.Customer", b =>
                {
                    b.HasOne("SSSClientTickets.Models.Client", "ClientRecNavigation")
                        .WithMany("Customers")
                        .HasForeignKey("ClientRec")
                        .IsRequired()
                        .HasConstraintName("FK_Customer_Client");

                    b.Navigation("ClientRecNavigation");
                });

            modelBuilder.Entity("SSSClientTickets.Models.Site", b =>
                {
                    b.HasOne("SSSClientTickets.Models.Client", "ClientRecNavigation")
                        .WithMany("Sites")
                        .HasForeignKey("ClientRec")
                        .IsRequired()
                        .HasConstraintName("FK_Site_Client");

                    b.Navigation("ClientRecNavigation");
                });

            modelBuilder.Entity("SSSClientTickets.Models.Ticket", b =>
                {
                    b.HasOne("SSSClientTickets.Models.Client", "ClientRecNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("ClientRec")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Client");

                    b.HasOne("SSSClientTickets.Models.Customer", "CustomerRecNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerRec")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Customer");

                    b.HasOne("SSSClientTickets.Models.Site", "SiteRecNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("SiteRec")
                        .HasConstraintName("FK_Ticket_Site");

                    b.HasOne("SSSClientTickets.Models.TicketStatus", "StatusRecNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("StatusRec")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_TicketStatus");

                    b.Navigation("ClientRecNavigation");

                    b.Navigation("CustomerRecNavigation");

                    b.Navigation("SiteRecNavigation");

                    b.Navigation("StatusRecNavigation");
                });

            modelBuilder.Entity("SSSClientTickets.Models.TicketAttachment", b =>
                {
                    b.HasOne("SSSClientTickets.Models.Ticket", "TicketRecNavigation")
                        .WithMany("TicketAttachments")
                        .HasForeignKey("TicketRec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TicketAttachment_Ticket");

                    b.Navigation("TicketRecNavigation");
                });

            modelBuilder.Entity("SSSClientTickets.Models.TicketTime", b =>
                {
                    b.HasOne("SSSClientTickets.Models.Ticket", "TicketRecNavigation")
                        .WithMany("TicketTimes")
                        .HasForeignKey("TicketRec")
                        .IsRequired()
                        .HasConstraintName("FK_TicketTime_Ticket");

                    b.Navigation("TicketRecNavigation");
                });

            modelBuilder.Entity("SSSClientTickets.Models.Client", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Sites");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SSSClientTickets.Models.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SSSClientTickets.Models.Site", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SSSClientTickets.Models.Ticket", b =>
                {
                    b.Navigation("TicketAttachments");

                    b.Navigation("TicketTimes");
                });

            modelBuilder.Entity("SSSClientTickets.Models.TicketStatus", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
